#!/bin/sh
#
# Convert development_guideline.yaml to coding-standard.md
# This script runs inside a container with yq available.
# Output goes to stdout.
#

set -e

YAML_FILE="development_guideline.yaml"

cat << 'EOF'
# Coding Standard for Infrastructure

> **Note**: This file is auto-generated from `development_guideline.yaml`.
> Do not edit this file directly. Edit the YAML file instead and run `./generate-coding-standard.sh`.

EOF

echo "## Directory Structure"
echo ""

yq eval '.directory_structure.infrastructure.rules[] | "* " + .body' "$YAML_FILE"

NOTE=$(yq eval '.directory_structure.infrastructure.rules[0].note' "$YAML_FILE")
if [ "$NOTE" != "null" ]; then
    echo ""
    echo "$NOTE"
fi

echo ""

SECTIONS=$(yq eval '.coding_standards | keys | .[]' "$YAML_FILE")

for section in $SECTIONS; do
    SECTION_TITLE=$(echo "$section" | sed 's/_/ /g' | awk '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1')

    echo "## $SECTION_TITLE"
    echo ""

    yq eval ".coding_standards.$section.rules[] | \"* \" + .body" "$YAML_FILE"

    echo ""
done
